# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('big_image_path', models.CharField(max_length=200)),
                ('small_image_path', models.CharField(max_length=200)),
            ],
        ),
    ]
