# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
