# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='credit_video',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='video_path',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
