# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171107_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='page_name',
            field=models.CharField(default='titi', max_length=100),
            preserve_default=False,
        ),
    ]
